# Generated by Django 2.2.5 on 2019-09-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='postiton_time',
            new_name='position_time',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='company_name',
            field=models.CharField(default='', max_length=100, verbose_name='Наименовние места работы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperience',
            name='position',
            field=models.CharField(default='', max_length=50, verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
