# Generated by Django 2.2.5 on 2019-09-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190911_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltype',
            name='skill_level',
            field=models.IntegerField(default=0, max_length=3, verbose_name='Уровень владения'),
            preserve_default=False,
        ),
    ]
