# Generated by Django 2.2.5 on 2019-09-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_skilltype_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='skilltype',
            name='skill_level',
            field=models.IntegerField(verbose_name='Уровень владения'),
        ),
    ]
