# Generated by Django 2.2.5 on 2019-09-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190916_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/default_image.png', null=True, upload_to='media/pictures'),
        ),
    ]
