# Generated by Django 2.2.5 on 2019-09-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190920_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'pictures'),
        ),
    ]
