# Generated by Django 2.2.5 on 2019-09-20 05:45

import core.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190920_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media//', location='D:\\Projects\\portfolio_site_env\\portfolio_site\\media/'), upload_to=core.models.image_directory_path),
        ),
    ]
