# Generated by Django 2.2.5 on 2019-09-20 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190920_1555'),
        ('core', '0012_auto_20190920_1545'),
    ]

    operations = [
    ]
